void simulate(CKTcircuit *circuit, HASH_TAB *htab);
void r_g1_stamp(CKTcircuit *circuit, ELM_TAB *element);
void r_g2_stamp(CKTcircuit *circuit, ELM_TAB *element);
void v_stamp(CKTcircuit *circuit, ELM_TAB *element);
void i_g1_stamp(CKTcircuit *circuit, ELM_TAB *element);
void i_g2_stamp(CKTcircuit *circuit, ELM_TAB *element);
void l_dc_stamp(CKTcircuit *circuit, ELM_TAB *element);
void g_stamp(CKTcircuit *circuit, ELM_TAB *element);
void e_stamp(CKTcircuit *circuit, ELM_TAB *element);
void f_stamp(CKTcircuit *circuit, HASH_TAB *htab, ELM_TAB *element);
void h_stamp(CKTcircuit *circuit, HASH_TAB *htab, ELM_TAB *element);